### PR TITLE
[assign] fixed omp section

### PR DESCRIPTION
**Pull request by clonker**
this seems to work for me (8 threads)

### CODE REVIEW

**Comment by marscher** [comment]
thank you very much!

**Comment by marscher** [comment]
I just wonder what the problem was (like one or two elements differed from the orignal result)

**Comment by clonker** [comment]
The problem was some things missing in the omp private (...) and the globbing in your test script, which (at least on my machine) yielded the files in a different order than 0,1,2 :)

**Comment by marscher** [comment]
hehe, didnt expect that.

**Pull request merged**
